future: true
exclude:
- CONTRIBUTING.md

permalink: /activity/:year/:month/:title
paginate: 5
paginate_path: "activity/page:num"

sass:
  style: compressed
  sass_dir: _sass

# Gems
gems:
- jekyll-paginate
